 "use client";
import {useEffect,useState} from "react";

type Essay={id:number;title:string;author:string;age:number;topic:string;likes:number;text:string;comments:{author:string;body:string}[]};
const topics=["Science","Politics & Government","History","Environment","Technology","Education","Culture","Philosophy","Arts","Current Issues","Personal Experience"];
const seed:Essay[]=[
{id:1,title:"The Climate Crisis Isn't Just About the Planet — It's About People",author:"Taylor S.",age:17,topic:"Environment",likes:512,text:"Climate change is often discussed through charts, temperatures, and distant predictions. But the people living through its effects are not distant.\n\nWhen extreme weather disrupts a community, it can affect schools, homes, food systems, and the ability of families to recover. That means environmental conversations are also conversations about people, opportunity, and responsibility.\n\nYoung writers have a place in this discussion. We may not control every decision, but we can ask better questions, listen to people affected by change, and push for solutions that consider both the planet and the people who depend on it.",comments:[]},
{id:2,title:"AI: Opportunity or Threat for Future Generations?",author:"Jordan K.",age:16,topic:"Technology",likes:476,text:"Artificial intelligence is becoming part of school, work, creativity, and everyday life. The question is not simply whether AI is good or bad. The more useful question is how people choose to use it.\n\nStudents should learn how these tools work, where they can fail, and how to use them without giving up their own thinking.",comments:[]},
{id:3,title:"What Does Real Democracy Look Like in the 21st Century?",author:"Riley P.",age:18,topic:"Politics & Government",likes:443,text:"Democracy is more than voting every few years. It also depends on participation, informed disagreement, access to information, and the willingness to listen to people with different experiences.\n\nYoung people can practice those habits now: asking questions, checking sources, understanding opposing arguments, and discussing difficult issues without treating disagreement as a personal attack.",comments:[]},
{id:4,title:"Finding My Voice: What Writing Has Taught Me About Myself",author:"Sam W.",age:15,topic:"Personal Experience",likes:398,text:"I used to think writing was mostly about having the right answer. I have learned that sometimes writing is about asking a question clearly enough that other people want to think about it too.",comments:[]}
];

const icon=(t:string)=>({Science:"🔬","Politics & Government":"🏛️",History:"📜",Environment:"🌱",Technology:"💻",Education:"📚",Culture:"🎭",Philosophy:"💭",Arts:"🎨","Current Issues":"🗞️","Personal Experience":"✍️"} as any)[t]||"✦";

function Card({e,onOpen}:{e:Essay,onOpen:(e:Essay)=>void}){return <article className="card"><div className="card-cover">{icon(e.topic)}</div><div className="card-body"><span className={"tag "+(e.topic.includes("Politics")?"p":"")}>{e.topic}</span><h3><button style={{border:0,background:"none",padding:0,textAlign:"left",font:"inherit",color:"inherit"}} onClick={()=>onOpen(e)}>{e.title}</button></h3><div className="meta">By {e.author} · {e.age}</div><div className="stats"><span>♥ {e.likes}</span><span>💬 {e.comments.length}</span></div></div></article>}

export default function Home(){
 const [essays,setEssays]=useState<Essay[]>(seed),[view,setView]=useState<"home"|"explore"|"top"|"apply"|"article"|"admin"|"search">("home"),[selected,setSelected]=useState<Essay|null>(null),[query,setQuery]=useState("");
 const [apps,setApps]=useState<any[]>([]);
 const [liked,setLiked]=useState<number[]>([]);
 useEffect(()=>{try{setEssays(JSON.parse(localStorage.getItem("poly_essays")||"null")||seed);setApps(JSON.parse(localStorage.getItem("poly_apps")||"[]"));setLiked(JSON.parse(localStorage.getItem("poly_liked")||"[]"))}catch{}},[]);
 useEffect(()=>{localStorage.setItem("poly_essays",JSON.stringify(essays));localStorage.setItem("poly_apps",JSON.stringify(apps));localStorage.setItem("poly_liked",JSON.stringify(liked))},[essays,apps,liked]);
 const open=(e:Essay)=>{setSelected(e);setView("article");window.scrollTo(0,0)};
 const sorted=[...essays].sort((a,b)=>b.likes-a.likes);
 const results=essays.filter(e=>(e.title+" "+e.author+" "+e.topic+" "+e.text).toLowerCase().includes(query.toLowerCase()));
 const nav=(v:any)=>{setView(v);setSelected(null);window.scrollTo(0,0)};
 const like=()=>{if(!selected)return;const already=liked.includes(selected.id);setLiked(already?liked.filter(x=>x!==selected.id):[...liked,selected.id]);setEssays(essays.map(e=>e.id===selected.id?{...e,likes:e.likes+(already?-1:1)}:e));setSelected({...selected,likes:selected.likes+(already?-1:1)})};
 const comment=(body:string)=>{if(!selected||!body.trim())return;const next={author:"Reader",body};setEssays(essays.map(e=>e.id===selected.id?{...e,comments:[...e.comments,next]}:e));setSelected({...selected,comments:[...selected.comments,next]})};
 const apply=(ev:any)=>{ev.preventDefault();const f=new FormData(ev.currentTarget);const age=Number(f.get("age"));if(age<14||age>21){alert("Applications are for ages 14–21.");return}setApps([...apps,{name:f.get("name"),display:f.get("display"),age,topic:f.get("topic"),reason:f.get("reason"),writing:f.get("writing"),status:"Pending",date:new Date().toISOString()}]);ev.currentTarget.reset();alert("Application submitted.");nav("home")};
 const review=(i:number,status:string)=>setApps(apps.map((a,n)=>n===i?{...a,status}:a));
 return <><header className="header"><a className="brand" href="#" onClick={()=>nav("home")}><img src="/icon.svg" alt=""/><span>The Polymathic</span></a><nav className="nav"><a href="#!" onClick={()=>nav("home")}>Home</a><a href="#!" onClick={()=>nav("explore")}>Explore</a><a href="#!" onClick={()=>nav("top")}>Top Essays</a><a href="#!" onClick={()=>nav("apply")}>Become a Writer</a><a href="#!" onClick={()=>nav("explore")}>Writers</a><a href="#!" onClick={()=>nav("explore")}>Discussions</a></nav><form className="search" onSubmit={e=>{e.preventDefault();nav("search")}}><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search topics, authors, or keywords..."/></form></header>
 <main className="main">
 {view==="home"&&<><section className="hero"><div><div className="eyebrow">Student writers · ages 14–21</div><h1>Young Minds.<br/>Big Ideas.<br/><span>Real Conversations.</span></h1><p>The Polymathic is a place for student writers to inform, advocate, argue, question, and share the ideas that matter to them.</p><div className="actions"><button className="btn yellow" onClick={()=>nav("apply")}>✎ Become a Writer →</button><button className="btn alt" onClick={()=>nav("explore")}>Explore Essays →</button></div></div><div className="butterfly"><img src="/icon.svg" alt="Paper-wing butterfly"/></div></section>
 <section className="section"><div className="section-head"><div><div className="eyebrow">What people are reading</div><h2>Featured Essays</h2></div><button className="btn alt" onClick={()=>nav("explore")}>View all →</button></div><div className="grid">{essays.slice(0,4).map(e=><Card key={e.id} e={e} onOpen={open}/>)}</div></section>
 <section className="section"><div className="section-head"><div><div className="eyebrow">Explore</div><h2>Browse by Topic</h2></div></div><div className="topics">{topics.map(t=><button key={t} className="topic" onClick={()=>{setQuery(t);nav("search")}}>{icon(t)} {t}</button>)}</div></section>
 <section className="section"><div className="section-head"><div><div className="eyebrow">Reader favorites</div><h2>Top Essays</h2></div><button className="btn alt" onClick={()=>nav("top")}>View all →</button></div><div className="grid">{sorted.slice(0,4).map(e=><Card key={e.id} e={e} onOpen={open}/>)}</div></section>
 <section className="section"><div className="quote">“Different perspectives make a stronger world.”<small>THE POLYMATHIC</small></div></section></>}
 {view==="explore"&&<section className="page"><div className="eyebrow">Explore</div><h1 style={{font:"700 50px Georgia,serif"}}>Find something worth thinking about.</h1><div className="topics" style={{margin:"20px 0 30px"}}>{topics.map(t=><button key={t} className="topic" onClick={()=>{setQuery(t);nav("search")}}>{icon(t)} {t}</button>)}</div><div className="grid">{essays.map(e=><Card key={e.id} e={e} onOpen={open}/>)}</div></section>}
 {view==="top"&&<section className="page"><div className="eyebrow">Reader favorites</div><h1 style={{font:"700 50px Georgia,serif"}}>Top Essays</h1><div className="grid">{sorted.map(e=><Card key={e.id} e={e} onOpen={open}/>)}</div></section>}
 {view==="search"&&<section className="page"><div className="eyebrow">Search</div><h1 style={{font:"700 48px Georgia,serif"}}>Results for “{query}”</h1><div className="grid">{results.length?results.map(e=><Card key={e.id} e={e} onOpen={open}/>):<div className="empty" style={{gridColumn:"1/-1"}}>No essays found. Try another topic or keyword.</div>}</div></section>}
 {view==="article"&&selected&&<section className="page"><article className="article"><span className="tag">{selected.topic}</span><h1>{selected.title}</h1><div className="meta">By {selected.author} · age {selected.age}</div><div className="toolrow"><button className={"pill "+(liked.includes(selected.id)?"liked":"")} onClick={like}>♥ {selected.likes}</button><span className="pill">💬 {selected.comments.length} comments</span></div><div className="article-text">{selected.text}</div><div className="comments"><h2>Discussion</h2>{selected.comments.map((c,i)=><div className="comment" key={i}><b>{c.author}</b><p>{c.body}</p></div>)}<CommentForm onSubmit={comment}/></div></article></section>}
 {view==="apply"&&<section className="form"><div className="eyebrow">Join the community</div><h1 style={{font:"700 48px Georgia,serif"}}>Become a Writer</h1><p>Share something you care about. Applications are reviewed before publishing access is granted.</p><div className="formbox"><div className="notice">Writers must be between 14 and 21. Public profiles can use a display name rather than a legal name.</div><form onSubmit={apply} style={{marginTop:20}}><div className="fields"><Field name="name" label="Name" required/><Field name="age" label="Age" type="number" min="14" max="21" required/><Field name="display" label="Preferred display name" required/><div className="field"><label>Topic</label><select name="topic" required>{topics.map(t=><option key={t}>{t}</option>)}</select></div><Field name="reason" label="Why does this topic matter to you?" area full required/><Field name="writing" label="Your writing submission" area full required/><div className="field full"><label><input type="checkbox" required/> I agree to follow the community guidelines.</label></div></div><button className="btn yellow" style={{marginTop:18}}>Submit Application →</button></form></div></section>}
 {view==="admin"&&<section className="admin"><div className="eyebrow">Private review area</div><h1 style={{font:"700 48px Georgia,serif"}}>Writer Applications</h1><p>Demo dashboard. A production deployment should protect this route with real authentication and server-side authorization.</p>{apps.length?apps.map((a,i)=><div className="application" key={i}><div><span className="tag">{a.topic}</span><h3>{a.display} <span className="meta">({a.age})</span></h3><div className="meta">{a.name} · {new Date(a.date).toLocaleDateString()}</div><p><b>Why:</b> {a.reason}</p><p><b>Submission:</b> {a.writing}</p><p className="meta">Status: {a.status}</p></div><div className="appactions"><button className="approve" onClick={()=>review(i,"Approved")}>Approve</button><button className="review" onClick={()=>review(i,"Needs More Review")}>Needs More Review</button><button className="reject" onClick={()=>review(i,"Not Accepted")}>Not Accepted</button></div></div>):<div className="empty">No applications yet.</div>}</section>}
 </main><footer><div className="footerbrand"><img src="/icon.svg" alt=""/>The Polymathic</div><span>Young minds. Big ideas. Real conversations.</span><span>Prototype for a public launch.</span></footer></>
}
function Field({name,label,type="text",area=false,full=false,...rest}:any){return <div className={"field "+(full?"full":"")}><label>{label}</label>{area?<textarea name={name} {...rest}/>:<input name={name} type={type} {...rest}/>}</div>}
function CommentForm({onSubmit}:{onSubmit:(x:string)=>void}){const [v,setV]=useState("");return <form className="commentform" onSubmit={e=>{e.preventDefault();onSubmit(v);setV("")}}><input value={v} onChange={e=>setV(e.target.value)} placeholder="Add your perspective..."/><button className="btn">Post</button></form>}
